/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.character {
    export class Bullet_1_1UI extends View {
        public static  uiView:any ={"type":"View","props":{"width":25,"height":25},"compId":2,"child":[{"type":"Image","props":{"y":0,"x":0,"width":25,"skin":"icon/role.png","height":25},"compId":3}],"loadList":["icon/role.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(Bullet_1_1UI.uiView);
        }
    }
    REG("ui.character.Bullet_1_1UI",Bullet_1_1UI);
    export class Bullet_2_1UI extends View {
        public static  uiView:any ={"type":"View","props":{"width":25,"height":25},"compId":2,"child":[{"type":"Image","props":{"y":0,"x":0,"width":25,"skin":"icon/enemy.png","height":25},"compId":3}],"loadList":["icon/enemy.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(Bullet_2_1UI.uiView);
        }
    }
    REG("ui.character.Bullet_2_1UI",Bullet_2_1UI);
    export class EnemyUI extends View {
		public gun1:Laya.Sprite;
		public gun2:Laya.Sprite;
		public gun3:Laya.Sprite;
		public gun4:Laya.Sprite;
        public static  uiView:any ={"type":"View","props":{"width":125,"height":125},"compId":2,"child":[{"type":"Image","props":{"y":0,"x":0,"skin":"icon/enemy.png"},"compId":3},{"type":"Sprite","props":{"y":0,"x":62.5,"var":"gun1"},"compId":4},{"type":"Sprite","props":{"y":62.5,"x":0,"var":"gun2"},"compId":5},{"type":"Sprite","props":{"y":62.5,"x":125,"var":"gun3"},"compId":6},{"type":"Sprite","props":{"y":62.5,"x":62.5,"var":"gun4"},"compId":7}],"loadList":["icon/enemy.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(EnemyUI.uiView);
        }
    }
    REG("ui.character.EnemyUI",EnemyUI);
    export class RoleUI extends View {
		public gun1:Laya.Sprite;
		public gun2:Laya.Sprite;
		public gun3:Laya.Sprite;
        public static  uiView:any ={"type":"View","props":{"width":125,"height":125},"compId":2,"child":[{"type":"Image","props":{"y":0,"x":0,"skin":"icon/role.png"},"compId":3},{"type":"Sprite","props":{"y":0,"x":62.5,"var":"gun1"},"compId":4},{"type":"Sprite","props":{"y":62.5,"x":0,"var":"gun2"},"compId":5},{"type":"Sprite","props":{"y":62.5,"x":125,"var":"gun3"},"compId":6}],"loadList":["icon/role.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(RoleUI.uiView);
        }
    }
    REG("ui.character.RoleUI",RoleUI);
}
export module ui {
    export class GameUI extends View {
        public static  uiView:any ={"type":"View","props":{"width":1080,"height":1920},"loadList":[],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(GameUI.uiView);
        }
    }
    REG("ui.GameUI",GameUI);
    export class WelcomeUI extends View {
		public txt:Laya.Label;
        public static  uiView:any ={"type":"View","props":{"width":1080,"height":1920},"compId":2,"child":[{"type":"Label","props":{"y":948,"x":473.77685546875,"var":"txt","text":"100%","fontSize":50,"font":"Microsoft YaHei","color":"#ffffff"},"compId":3}],"loadList":[],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(WelcomeUI.uiView);
        }
    }
    REG("ui.WelcomeUI",WelcomeUI);
}